package yygl.base.pojo.po;

import java.util.Date;

public class Sysuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.ID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.USERID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.USERNAME
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.GROUPID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.PWD
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.CONTACT
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.ADDR
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.EMAIL
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.USERSTATE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String userstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.REMARK
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.CREATETIME
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.SEX
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.PHONE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.MOVEPHONE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String movephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.FAX
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.LASTUPDATE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String lastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.VCHAR1
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.VCHAR2
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.VCHAR3
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.VCHAR4
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String vchar4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.VCHAR5
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String vchar5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSUSER.SYSID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    private String sysid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.ID
     *
     * @return the value of SYSUSER.ID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.ID
     *
     * @param id the value for SYSUSER.ID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.USERID
     *
     * @return the value of SYSUSER.USERID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.USERID
     *
     * @param userid the value for SYSUSER.USERID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.USERNAME
     *
     * @return the value of SYSUSER.USERNAME
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.USERNAME
     *
     * @param username the value for SYSUSER.USERNAME
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.GROUPID
     *
     * @return the value of SYSUSER.GROUPID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.GROUPID
     *
     * @param groupid the value for SYSUSER.GROUPID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.PWD
     *
     * @return the value of SYSUSER.PWD
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.PWD
     *
     * @param pwd the value for SYSUSER.PWD
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.CONTACT
     *
     * @return the value of SYSUSER.CONTACT
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.CONTACT
     *
     * @param contact the value for SYSUSER.CONTACT
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.ADDR
     *
     * @return the value of SYSUSER.ADDR
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.ADDR
     *
     * @param addr the value for SYSUSER.ADDR
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.EMAIL
     *
     * @return the value of SYSUSER.EMAIL
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.EMAIL
     *
     * @param email the value for SYSUSER.EMAIL
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.USERSTATE
     *
     * @return the value of SYSUSER.USERSTATE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getUserstate() {
        return userstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.USERSTATE
     *
     * @param userstate the value for SYSUSER.USERSTATE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setUserstate(String userstate) {
        this.userstate = userstate == null ? null : userstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.REMARK
     *
     * @return the value of SYSUSER.REMARK
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.REMARK
     *
     * @param remark the value for SYSUSER.REMARK
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.CREATETIME
     *
     * @return the value of SYSUSER.CREATETIME
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.CREATETIME
     *
     * @param createtime the value for SYSUSER.CREATETIME
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.SEX
     *
     * @return the value of SYSUSER.SEX
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.SEX
     *
     * @param sex the value for SYSUSER.SEX
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.PHONE
     *
     * @return the value of SYSUSER.PHONE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.PHONE
     *
     * @param phone the value for SYSUSER.PHONE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.MOVEPHONE
     *
     * @return the value of SYSUSER.MOVEPHONE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getMovephone() {
        return movephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.MOVEPHONE
     *
     * @param movephone the value for SYSUSER.MOVEPHONE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setMovephone(String movephone) {
        this.movephone = movephone == null ? null : movephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.FAX
     *
     * @return the value of SYSUSER.FAX
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.FAX
     *
     * @param fax the value for SYSUSER.FAX
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.LASTUPDATE
     *
     * @return the value of SYSUSER.LASTUPDATE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.LASTUPDATE
     *
     * @param lastupdate the value for SYSUSER.LASTUPDATE
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setLastupdate(String lastupdate) {
        this.lastupdate = lastupdate == null ? null : lastupdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.VCHAR1
     *
     * @return the value of SYSUSER.VCHAR1
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.VCHAR1
     *
     * @param vchar1 the value for SYSUSER.VCHAR1
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1 == null ? null : vchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.VCHAR2
     *
     * @return the value of SYSUSER.VCHAR2
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.VCHAR2
     *
     * @param vchar2 the value for SYSUSER.VCHAR2
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2 == null ? null : vchar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.VCHAR3
     *
     * @return the value of SYSUSER.VCHAR3
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.VCHAR3
     *
     * @param vchar3 the value for SYSUSER.VCHAR3
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3 == null ? null : vchar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.VCHAR4
     *
     * @return the value of SYSUSER.VCHAR4
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getVchar4() {
        return vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.VCHAR4
     *
     * @param vchar4 the value for SYSUSER.VCHAR4
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setVchar4(String vchar4) {
        this.vchar4 = vchar4 == null ? null : vchar4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.VCHAR5
     *
     * @return the value of SYSUSER.VCHAR5
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getVchar5() {
        return vchar5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.VCHAR5
     *
     * @param vchar5 the value for SYSUSER.VCHAR5
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setVchar5(String vchar5) {
        this.vchar5 = vchar5 == null ? null : vchar5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSUSER.SYSID
     *
     * @return the value of SYSUSER.SYSID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public String getSysid() {
        return sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSUSER.SYSID
     *
     * @param sysid the value for SYSUSER.SYSID
     *
     * @mbggenerated Sun Nov 22 08:03:41 CST 2015
     */
    public void setSysid(String sysid) {
        this.sysid = sysid == null ? null : sysid.trim();
    }
}